Ext.define('Semblance.generator.person.Language', {
    extend: 'Semblance.generator.random.Array',
    alias: 'semblance.person.language',
    items: [
        'Mandarin',
        'English',
        'Spanish',
        'Arabic',
        'Bengali',
        'Hindi',
        'Russian',
        'Portuguese',
        'Japanese',
        'German',
        'Wu',
        'Javanese',
        'Korean',
        'French',
        'Turkish',
        'Vietnamese',
        'Telugu',
        'Cantonese',
        'Marathi',
        'Tamil',
        'Italian',
        'Urdu',
        'Min Nan',
        'Jinyu',
        'Gujarati'
    ]
});
